# docker-compose.yml - للبيئات المعقدة

version: '3.8'

services:
  hpo_runner:
    # بناء الصورة من Dockerfile في المجلد الحالي
    build: .

    # اسم الحاوية
    container_name: hpo_production_system

    # ربط المجلدات (Volumes)
    # هذا يربط الكود المحلي داخل الحاوية،
    # مما يسمح بالتعديل على الكود دون الحاجة لإعادة بناء الصورة.
    # كما أنه يضمن حفظ النتائج (قاعدة البيانات والتقارير) على الجهاز المضيف.
    volumes:
      - .:/app

    # الأمر الذي سيتم تشغيله عند بدء الخدمة
    # يمكنك تغييره لتشغيل مهام مختلفة
    # مثال: command: ["--quick"]
    # مثال: command: ["--check"]
    # الافتراضي هو تشغيل التحسين الكامل
    command: [""] # سيؤدي هذا إلى تشغيل run_hpo.py بدون وسيطات (التحسين الكامل)

    # إبقاء الحاوية قيد التشغيل (مفيد للتصحيح)
    # tty: true
    # stdin_open: true

    # إعدادات الموارد (اختياري)
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '2.0'
    #       memory: '4G'