name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          if [ -f dev-requirements.txt ]; then pip install -r dev-requirements.txt; fi
      - name: Run pre-commit
        run: |
          pip install pre-commit
          pre-commit run --all-files || true
      - name: Run tests
        run: |
          pytest -q --maxfail=1
      - name: Upload coverage
        if: success()
        uses: codecov/codecov-action@v3